name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    env:
      DEVELOPER_DIR: /Applications/Xcode_13.app/Contents/Developer

    strategy:
      matrix:
        os: [ubuntu-20.04, macos-11]
        swift: ["5.3", "5.5"]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
